server:
  port: 8761

spring:
  application:
    name: lab-a01-app-service-registry

  cloud:
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

